# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        #public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\OffersQueryService:
        public: true
        arguments:
          - '@request_stack'
          - '@App\Repository\OfferRepository'
          - '@security.helper'
          - '@security.authorization_checker'

    App\EventSubscriber\OfferApplianceSubscriber:
        arguments:
          - '@swiftmailer.mailer.default'
          - '@twig'
          - '%env(MAILER_SENDER_OFFER_APPLIANCE)%'
        tags:
            - { name: kernel.event_subscriber }

    App\EventSubscriber\OfferEditionSubscriber:
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    App\Twig\AppExtension:
        tags:
            - { name: twig.extension }

    App\Twig\AppRuntime:
        arguments: ['@request_stack']
        tags:
            - { name: twig.runtime }